#!/usr/bin/env wish# diffusion_coefficient_gui.tcl --
#
# UI generated by GUI Builder Build 146 on 2019-09-18 20:38:55 from:
#    /Users/toni/compile/vmd_diffusion_coefficient/diffusion_coefficient_gui.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE'
#    '# END USER CODE'
# and code inside the callback subroutines will be round-tripped.
# The proc names 'ui' and 'init' are reserved.
#

package require Tk 8.4

# Declare the namespace for this dialog
namespace eval diffusion_coefficient_gui {}

# Source the ui file, which must exist
set diffusion_coefficient_gui::SCRIPTDIR [file dirname [info script]]
source [file join $diffusion_coefficient_gui::SCRIPTDIR diffusion_coefficient_gui_ui.tcl]

# BEGIN USER CODE
# ----------------------------------------
# GUI functions for computing density profiles.
# ----------------------------------------


# This code is a mess because it can be loaded back in guibuilder.
package provide diffusion_coefficient_gui 1.2

namespace eval diffusion_coefficient_gui {
    variable utf8_tau "\u03C4"
    variable utf8_A2 "\uc5\ub2"
    variable already_registered 0

    variable w .diffusion_coefficient
    variable abort_button $w.abort_button
    # http://www.small-icons.com/packs/24x24-free-application-icons.htm
    variable save_icon_data {
	R0lGODlhGAAYAHcAACH5BAEAAA4ALAAAAAAYABgAp+bo5/f3+CprsN7Z1v///mV7l4igtmu+6t/g
	4fDx8dXT1Ojp6ePk5dvc3QEAAP///xdarP/9+dXW2Ozt7f3+/mzF8HXK8XnN8hxhr1y77OLj5YLS
	9X3V+byvstDR04La/9HS1H3S9Nze3vX29hyc5VtVX2xmc3HH8N3f4Pj5+Gm756Ganf39/ozZ+Pn5
	+n3O9JyPkPP19JLT8UI5RjuLzPb49+bm5ce+wWVebXZxfFyt4rWrrmK/7v//+zSJzrnl+qvd9nrV
	/jN9xHDJ8hWa5H52hkm17uvs7dLu/Oze2yui5yFsu/j7+U1HVFVOXOHi46upsz6u6zgxO6akr0Sy
	7KueotnZ2+/w8DKn5zmr6b+1uGd7l1W16LWmpo6Lkkit5leCpLSnqLiqrGmSuKqdn2fI9nfQ+aWZ
	mS1usiWe5VGr5NjX15WEf4qiuK+ipPv7/GTI+oTV9aGUlWt5kcK3trq3uvz+/VCp4Pr6+vv7+y93
	vnvT+WvK90hBTWfD8nOJpW/M9+Tg3NTU13PO9/Ds6zin5PXy7yhyvEKp5ZONlYDU9VC26kKf3Gqz
	2pSRm4XP7yKa3szt+3tzgIDN7rPh99DQ0qCWmenq7Cl3wz+b2jGi4o3Z9tfW1/z8/F5WY6/g90yg
	21KAo1R+n7Xk+IzR8I6JmtPLzl226kea1s7N0Fy/8Eyx55jV8nNvfc3FyNfY2TWDxzeP0jmFyUOi
	4IeBkYDV+0ppg1F/pTGFysvAw8LAx3nJ7Pr9+6WeoBxotouHl9ra3IR/j1C67vHy8vn39VO46lSv
	5FKt5kSh30uz6ESW1JyUlt/h4puZoPr7+kKU0kCQ0NbX2NfW2tbV2GfD71a87yx7xla668Xt/7y4
	utDFyT1PZU+37mjC8CdzwC59yHG43NTKzOvp52a+7L7o+Vmz5tja29DIy8S5vNrZ2GjA773r/zqT
	1Cig4IB6hIuFj53X8yZwvp+dp23I7rzn+6Xa86DY9GPB8MDp+0md2dnY2D6r5YWBidXU1TyX2AAA
	AAj/ABGtykBQhYoDCBMqVKGj2CkHEL9EQoJvXZIeETJq7PGg44Mk2MYdg1gOySZFHM7FSMCyZY0V
	vVYoMMWhBRc1DoyRCxGHg6srE4IKJWYLXKMV4TjEsalDDb0QG/bcOLKgqlVDYD58sKRtz4YNLWbd
	+XHhhRl0ABioXUtIVK0gy3KZefFiA7KxFi4M0qIBgd+/4kJ9CALjxqALF0IwAjVqiAVAHVA0mEzZ
	xjYwtxJpAWQhb6Z8lCqc4LPDioTTqK3UyVbHww4+J05Y8IfqE7UKZaroU8C7dz9Oa9akq1KmQoUh
	7JQB4eEHzp82BqJLn97mDxw/6irEegZE1Zg5WwqI/x9PXvyWOWPudfMBrZ6wLg8IyJ9Pn/6DLtV4
	+KBhzwgdFyO44AIeebzxRicsJEgBBXngQQc3GeBCAzxUdMCELlBMIU8zjnjxDj/uSJKDCV7Y0YER
	13wjCytRiDFCADDGKOOMYlCxiDWwyJBFGCzFMEINKaTAhDO82LEgBSkME0YUyWAihAxYuHEFFL8E
	U0QrJuBQghNN9DGDFCXE4EYWX3gjBClKkHEJMK9IE800gggCAggeeFBJKiAcQQYW+8SjxyNpnGED
	AIQWauihZyhRyBJ6TEKCHAxMUQotRYyIgydcegnmAnKkockSh+xCBAwimNOACCKg4BczTzyhwasI
	oCkAAwnt+ILBPESwEcgAvPbqq6+BsEECJBBgAEGxaAig7LLMMouGsccGBAA7
    }
    variable stop_icon_data {
	R0lGODlhGAAYAHcAACH5BAEAAAAALAAAAAAYABgApwEAAP////RiS/RxVaUBA+4VEvJGSe4WEu0N
	D/R5W/RyV+4bE+4TEfR1WfbFyPRuUvZ6XfR6XesYC/mdgfRqTO4XEvR2Wd0GAe4cEu4QEPILDvR3
	WsorK/RkSvBFQeIZIsUVFuaqr6IBBe4PD8cKCvRyVe4YE+4SEJgAA+IGAe4REPAgFe0LDvR1WO0M
	DsMGCeyIj6wBBfEuNfBEPugKAOZCRuIWDuU4OZIAAu9DQe0rMvZ8X/EeEvUiHPDIzfEcFO9VUug6
	O/FVVfRpT7sDB4sAAfEbEssAAO0OD/AYEe8TEfYaGvEfFOxdYuguNfArM98AAO8YE/mcgvRzWPZ5
	XOQHAKAAA+4ZE+1vdu4SEdFfYekWCPIKDu4YEvR5WvRxU+aHifR4WtFKS/EbDv339fEcD/RuUMYX
	Gd8KAvRpS9wRDeE3OcoSFPMhDcsYGfmxmfR0WfMTEvmzmvZNNcwLDPRsTrADBtArLvmcgfMbDuxC
	P+wuNu8dFPRvVOQRBs4RFONBRskJCuQLB+8XEtAIC7sTFdsfIPE/RPWBYfMhFMkRE/RyVvAYDtEq
	Ke0tNeYrMvJWVvV3WOQtKsIMEPYJDvRmTPmIb+gqMvRrUPMkFvNYV/NjSMgRD/mhhPhEM+8VEvJH
	SvRtUuMQCfislfEZEtEPEvRtUPMOEPFARvmokPRvT/RtTM4JC/MIDvmqlP34+PZnS/QaE/IpEPmw
	luE0K/CdpfB7g/AVDPQMDu8tNew5KfN5W/gVGfZvU/mnjvIMDuc2OfZQON44PLoQEeILDuAAAPmc
	gOQAAOE4PdkcGfiEa/RzV/QpHvPIzb0UFtcVEPmPddoGAPIhFr4FCOg9QO/T1fMXE/QQEPV+XfIf
	FNoxNcEcHPV5W/NAMOYOAuMMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
	AAj/AAEIHCjjkIGDCA2AQiVjoEOHTzTJMTah4gQpUvB08tDw4cAnkN7s2AGhJAQqVHYlQOQhl0cA
	OoTMghChZs0EOBN4CYPNg6OHMUdtCKNzg1ELSBs0aAGHW449Ay8BcbXUgtIWU6YsU8B1gNcSkXI4
	AfAISKoSi7gq8Mp2wJcvD+KGelBCjxNqvvqYoVBH1SoKgE09SLOpEqYhHRIP6QWsBjQBkCNLnkz5
	Rg1LtgK8ChAigOcAMBx8djAjABnPM24AUlYrADFBKYqJhgIlQJNjTQJ8CBAkSIAZa4TBQuYZhp8t
	zQLQoBHggqwLugNgwRJAkqFSwbZoK+7NR4AqVQKo/2kDffdnCYT+zLmTjA7nb95TpAgA5giYABIC
	cJAgIRMrNrp05lkjaFTTXDSieeYALfrlsYI0gSjSDSdaaEECBjZsw4ENiRwhhhggiPIMB8MYscAP
	JEziCQ9ljMHECitkwwMTfPzAyC1JLGBEEqREEUUsL8TgBjMYFLnAkQtccYUJJnRRQQUHRPmJNSTY
	AUAMZ/QwSJNPRnlAAWCCyQADSsQR5EAigNCDEmGOyUAWWZxwggoZZHDNCyI8ZAUIS6gwZ50jBIoE
	EgggcMo0KLyEgjNLuFBooS64wMKkuBCR6EsA4FAILxr8osGnXHDRCiVE4IDpQEWIQMCqrK5qRREe
	BQEEADs=
    }
}

# VMD-specific stuff
set diffusion_coefficient_gui::in_vmd \
    [string length [info proc vmd_install_extension]]
if { $diffusion_coefficient_gui::in_vmd } {
    package require diffusion_coefficient
} else {
    #  Kludge to run outside VMD
    namespace eval ::diffusion_coefficient:: {}
    array set ::diffusion_coefficient::arg {}
}


# Tweak the icon
proc diffusion_coefficient_gui::fixup_ui_icons {} {
    variable w
    image create photo SaveGIF -data $diffusion_coefficient_gui::save_icon_data
    image create photo StopGIF -data $diffusion_coefficient_gui::stop_icon_data
    $w.save_button configure -image SaveGIF
    $w.abort_button configure -image StopGIF
}
 


# Register menu if possible
proc diffusion_coefficient_gui::register_menu {} {
    variable already_registered
    if {$already_registered==0} {
	incr already_registered
	vmd_install_extension diffusion_coefficient_gui \
	    diffusion_coefficient_gui::diffusion_coefficient_tk \
	    "Analysis/Diffusion Coefficient Tool"
    }
}


# Called right upon menu action
proc diffusion_coefficient_gui::diffusion_coefficient_tk {} {
#    puts "In diffusion_coefficient_tk"
    variable diffusion_coefficient_window
    if { [winfo exists .diffusion_coefficient] } {
	wm deiconify $diffusion_coefficient_window
    } else {
	set diffusion_coefficient_window [ toplevel ".diffusion_coefficient" ]
	wm title $diffusion_coefficient_window "Diffusion Coefficient Tool"
	diffusion_coefficient_gui::ui $diffusion_coefficient_window; # diffusion_coefficient_gui::init is now obsolete
	fixup_ui_icons
    }
    reset_interval_button_command
    reset_lags_button_command
    return $diffusion_coefficient_window
}

proc diffusion_coefficient_gui::help_docs {} {
    vmd_open_url https://github.com/giorginolab/vmd_diffusion_coefficient/
}

proc diffusion_coefficient_gui::help_about {} {
    variable diffusion_coefficient_window
    tk_messageBox -title "About" -parent $diffusion_coefficient_window -message \
"
VMD Diffusion Coefficient Tool

Version [package versions diffusion_coefficient]

Toni Giorgino <www.giorginolab.it>
National Research Council of Italy (CNR)

Copyright (c) 2010-2019

Previous versions: 
Computational Biophysics Group
Research Programme on Biomedical Informatics (GRIB-IMIM)
Universitat Pompeu Fabra (UPF)

"
    
}
# END USER CODE

# BEGIN CALLBACK CODE
# ONLY EDIT CODE INSIDE THE PROCS.

# diffusion_coefficient_gui::_checkbutton_1_command --
#
# Callback to handle _checkbutton_1 widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_checkbutton_1_command args {}

# diffusion_coefficient_gui::_checkbutton_2_command --
#
# Callback to handle _checkbutton_2 widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_checkbutton_2_command args {}

# diffusion_coefficient_gui::_checkbutton_3_command --
#
# Callback to handle _checkbutton_3 widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_checkbutton_3_command args {}

# diffusion_coefficient_gui::_checkbutton_4_command --
#
# Callback to handle _checkbutton_4 widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_checkbutton_4_command args {}

# diffusion_coefficient_gui::_entry_1_invalidcommand --
#
# Callback to handle _entry_1 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_1_invalidcommand args {}

# diffusion_coefficient_gui::_entry_1_validatecommand --
#
# Callback to handle _entry_1 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_1_validatecommand args {}

# diffusion_coefficient_gui::_entry_1_xscrollcommand --
#
# Callback to handle _entry_1 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_1_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_2_invalidcommand --
#
# Callback to handle _entry_2 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_2_invalidcommand args {}

# diffusion_coefficient_gui::_entry_2_validatecommand --
#
# Callback to handle _entry_2 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_2_validatecommand args {}

# diffusion_coefficient_gui::_entry_2_xscrollcommand --
#
# Callback to handle _entry_2 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_2_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_3_invalidcommand --
#
# Callback to handle _entry_3 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_3_invalidcommand args {}

# diffusion_coefficient_gui::_entry_3_validatecommand --
#
# Callback to handle _entry_3 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_3_validatecommand args {}

# diffusion_coefficient_gui::_entry_3_xscrollcommand --
#
# Callback to handle _entry_3 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_3_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_4_invalidcommand --
#
# Callback to handle _entry_4 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_4_invalidcommand args {}

# diffusion_coefficient_gui::_entry_4_validatecommand --
#
# Callback to handle _entry_4 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_4_validatecommand args {}

# diffusion_coefficient_gui::_entry_4_xscrollcommand --
#
# Callback to handle _entry_4 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_4_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_5_invalidcommand --
#
# Callback to handle _entry_5 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_5_invalidcommand args {}

# diffusion_coefficient_gui::_entry_5_validatecommand --
#
# Callback to handle _entry_5 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_5_validatecommand args {}

# diffusion_coefficient_gui::_entry_5_xscrollcommand --
#
# Callback to handle _entry_5 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_5_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_6_invalidcommand --
#
# Callback to handle _entry_6 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_6_invalidcommand args {}

# diffusion_coefficient_gui::_entry_6_validatecommand --
#
# Callback to handle _entry_6 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_6_validatecommand args {}

# diffusion_coefficient_gui::_entry_6_xscrollcommand --
#
# Callback to handle _entry_6 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_6_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_7_invalidcommand --
#
# Callback to handle _entry_7 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_7_invalidcommand args {}

# diffusion_coefficient_gui::_entry_7_validatecommand --
#
# Callback to handle _entry_7 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_7_validatecommand args {}

# diffusion_coefficient_gui::_entry_7_xscrollcommand --
#
# Callback to handle _entry_7 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_7_xscrollcommand args {}

# diffusion_coefficient_gui::_entry_8_invalidcommand --
#
# Callback to handle _entry_8 widget option -invalidcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_8_invalidcommand args {}

# diffusion_coefficient_gui::_entry_8_validatecommand --
#
# Callback to handle _entry_8 widget option -validatecommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_8_validatecommand args {}

# diffusion_coefficient_gui::_entry_8_xscrollcommand --
#
# Callback to handle _entry_8 widget option -xscrollcommand
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::_entry_8_xscrollcommand args {}

# diffusion_coefficient_gui::abort_button_command --
#
# Callback to handle abort_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::abort_button_command args {}

# diffusion_coefficient_gui::button_help_command --
#
# Callback to handle button_help widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::button_help_command args {
    help_docs
}

# diffusion_coefficient_gui::plot_d_button_command --
#
# Callback to handle plot_d_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::plot_d_button_command args {
    variable ::diffusion_coefficient::arg
    variable diffusion_coefficient_window
    variable utf8_tau
    variable utf8_A2
    variable abort_button

    $abort_button configure -state normal
    if [ catch {
	puts "diffusion_coefficient) Equivalent command: diffusion_coefficient -d range [::diffusion_coefficient::get_cli_equivalent]"
	
	set ND [::diffusion_coefficient::nd]
	lassign [::diffusion_coefficient::compute_avg_msd] tlist msdlist

	set fit [::diffusion_coefficient::msd_fit $tlist $msdlist]
	set a [lindex $fit 0]
	set b [lindex $fit 2]
	set t0 [lindex $tlist 0]
	set t1 [lindex $tlist end]

	set dlist [::diffusion_coefficient::msd_to_d $tlist $msdlist]

	set title [format "%d-dimensional diffusion coefficient, D = MSD/(2*$ND*$utf8_tau)" $ND]
	set mpl [multiplot -x $tlist -y $dlist -plot \
		     -title $title \
		     -xlabel "Lag time $utf8_tau (ns)" \
		     -ylabel "D ($utf8_A2/ns)" \
		     -marker point -radius 2 -fillcolor "#ff0000" -color "#ff0000" ]
	$mpl draw line $t0 $a $t1 $a -dash .
	# puts "	$mpl draw line $t0 $a $t1 $a -dash . "
    } e ] {
	tk_messageBox -title Error -message $e -icon error \
	    -parent $diffusion_coefficient_window 
    }
    $abort_button configure -state disabled

}

# diffusion_coefficient_gui::plot_msd_button_command --
#
# Callback to handle plot_msd_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::plot_msd_button_command args {
    variable diffusion_coefficient_window
    variable utf8_tau
    variable utf8_A2
    variable abort_button

    $abort_button configure -state normal
    if [ catch {
	puts "diffusion_coefficient) Equivalent command: diffusion_coefficient -msd range [::diffusion_coefficient::get_cli_equivalent]"

	set ND [::diffusion_coefficient::nd]
	lassign [::diffusion_coefficient::compute_avg_msd] tlist msdlist
	
	set fit [::diffusion_coefficient::msd_fit $tlist $msdlist]
	set a [expr 2.0 * $ND * [lindex $fit 0] ];	  # MSD = 2 E D tau
	set b [lindex $fit 2]
	set t0 [lindex $tlist 0]
	set t1 [lindex $tlist end]
	set y0 [expr $a * $t0 + $b]
	set y1 [expr $a * $t1 + $b]
	
	set mpl [multiplot -x $tlist -y $msdlist -plot \
		     -title "Mean square displacement with linear fit" \
		     -xlabel "Lag time $utf8_tau (ns)" \
		     -ylabel "MSD ($utf8_A2)" \
		     -marker point -radius 2 -fillcolor "#ff0000" -color "#ff0000" ]

	$mpl draw line $t0 $y0 $t1 $y1 -dash .
    } e ] {
	tk_messageBox -title Error -message $e -icon error \
	    -parent $diffusion_coefficient_window 
    }
    $abort_button configure -state disabled

}

# diffusion_coefficient_gui::reset_interval_button_command --
#
# Callback to handle reset_interval_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::reset_interval_button_command args {
    ::diffusion_coefficient::set_default_interval
}

# diffusion_coefficient_gui::reset_lags_button_command --
#
# Callback to handle reset_lags_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::reset_lags_button_command args {
    ::diffusion_coefficient::set_default_lags
}

# diffusion_coefficient_gui::save_button_command --
#
# Callback to handle save_button widget option -command
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::save_button_command args {
    variable diffusion_coefficient_window
    variable abort_button
    set fn [tk_getSaveFile -parent $diffusion_coefficient_window -filetypes {{{CSV Files} {.csv}} {{All files} *}} ]
    if {$fn != ""} {
	$abort_button configure -state normal
	if [ catch {::diffusion_coefficient::save_to_file $fn} e] {
	    tk_messageBox -title Error -message $e -icon error -parent $diffusion_coefficient_window
	}
	$abort_button configure -state disabled
    }
}

# diffusion_coefficient_gui::abort_button_command --
#
# Legacy command found in callback code. Add user comments inside body.
#
# ARGS:
#    <NONE>
#
proc diffusion_coefficient_gui::abort_button_command args {
    set ::diffusion_coefficient::abort_flag 1
}

# END CALLBACK CODE

# diffusion_coefficient_gui::init --
#
#   Call the optional userinit and initialize the dialog.
#   DO NOT EDIT THIS PROCEDURE.
#
# Arguments:
#   root   the root window to load this dialog into
#
# Results:
#   dialog will be created, or a background error will be thrown
#
proc diffusion_coefficient_gui::init {root args} {
    # Catch this in case the user didn't define it
    catch {diffusion_coefficient_gui::userinit}
    if {[info exists embed_args]} {
	# we are running in the plugin
	diffusion_coefficient_gui::ui $root
    } elseif {$::argv0 == [info script]} {
	# we are running in stand-alone mode
	wm title $root diffusion_coefficient_gui
	if {[catch {
	    # Create the UI
	    diffusion_coefficient_gui::ui  $root
	} err]} {
	    bgerror $err ; exit 1
	}
    }
    catch {diffusion_coefficient_gui::run $root}
}
diffusion_coefficient_gui::init .

